Portability: look for GNU utilities

diff --git a/simplesnap b/simplesnap
--- a/simplesnap
+++ b/simplesnap
@@ -105,6 +105,14 @@ done
 SSHCMD="${SSHCMD:-ssh}"
 WRAPCMD="${WRAPCMD:-simplesnapwrap}"
 
+DATE="gdate"
+gdate &> /dev/null || DATE="date"
+SED="gsed"
+gsed &> /dev/null || SED="sed"
+GREP="ggrep"
+ggrep &> /dev/null || GREP="grep"
+
+
 # Validating
 [ -n "$SSHCMD" ] || syntaxerror "Invalid SSH command: $SSHCMD"
 [ -n "$STORE" ] || syntaxerror "Missing --store"
@@ -113,9 +121,9 @@ WRAPCMD="${WRAPCMD:-simplesnapwrap}"
 
 PATTERN="^[a-zA-Z0-9_/. -]\+\$"
 
-echo "_${STORE}" | grep -qv " " || syntaxerror "Space in --store: ${STORE}"
-echo "_${SETNAME}" | grep -q "${PATTERN}" || syntaxerror "Invalid characters in setname \"${SETNAME}\"; pattern is \"${PATTERN}\""
-echo "_${SETNAME}" | grep -qv '^_-' || syntaxerror "Set name cannot begin with a dash: \"${SETNAME}\""
+echo "_${STORE}" | $GREP -qv " " || syntaxerror "Space in --store: ${STORE}"
+echo "_${SETNAME}" | $GREP -q "${PATTERN}" || syntaxerror "Invalid characters in setname \"${SETNAME}\"; pattern is \"${PATTERN}\""
+echo "_${SETNAME}" | $GREP -qv '^_-' || syntaxerror "Set name cannot begin with a dash: \"${SETNAME}\""
 TEMPLATE="__simplesnap_${SETNAME}_"
 
 MOUNTPOINT="`zfs list -H -o mountpoint -t filesystem \"${STORE}\"`"
@@ -127,7 +135,7 @@ cd "${MOUNTPOINT}"
 # template - $1
 # dataset - $2
 listsnaps () {
-   runzfs list -t snapshot -r -d 1 -H -o name "$2" | grep "@$1" || true
+   runzfs list -t snapshot -r -d 1 -H -o name "$2" | $GREP "@$1" || true
 }
 
 CHECKRETVAL=0
@@ -135,12 +143,12 @@ CHECKRETVAL=0
 checkbackups () {
   CHECKHOST="$1"
   DATASETS="`runzfs list -t filesystem,volume -o name -H -r \"${STORE}/${HOST}\"`"
-  CUTOFF="`date -d \"${CHECKMODE}\" +%s`"
+  CUTOFF="`$DATE -d \"${CHECKMODE}\" +%s`"
   for CHECKDS in ${DATASETS}; do
     FOUNDOK=0
     # Extract timestamps
-    for TIMESTAMP in listsnaps "$TEMPLATE" "$CHECKDS" | sed 's/^.*_\([^_]\+__\)$/\1/'; do
-        TSSEC=`date -d "${TIMESTAMP}" +%s`
+    for TIMESTAMP in listsnaps "$TEMPLATE" "$CHECKDS" | $SED 's/^.*_\([^_]\+__\)$/\1/'; do
+        TSSEC=`$DATE -d "${TIMESTAMP}" +%s`
         if [ "$TSSEC" -gt "$CUTOFF" ]; 
             then FOUNDOK=1
         fi
@@ -211,7 +219,7 @@ reap () {
        else
          for REMOVAL in ${SNAPSTOREMOVE}; do
             logit "Destroying snapshot ${REMOVAL}"
-            echo "_${REMOVAL}" | grep -q '@' || exiterror "PANIC: snapshot name doesn not contain @"
+            echo "_${REMOVAL}" | $GREP -q '@' || exiterror "PANIC: snapshot name doesn not contain @"
             runzfs destroy "${REMOVAL}"
          done
        fi
diff --git a/simplesnapwrap b/simplesnapwrap
--- a/simplesnapwrap
+++ b/simplesnapwrap
@@ -34,10 +34,18 @@ runzfs () {
   $ZFSCMD "$@"
 }
 
+DATE="gdate"
+gdate &> /dev/null || DATE="date"
+SED="gsed"
+gsed &> /dev/null || SED="sed"
+GREP="ggrep"
+ggrep &> /dev/null || GREP="grep"
+
+
 # template - $1
 # dataset - $2
 listsnaps () {
-   $ZFS list -t snapshot -r -d 1 -H -o name "$2" | grep "@$1" || true
+   $ZFS list -t snapshot -r -d 1 -H -o name "$2" | $GREP "@$1" || true
 }
 
 PATTERN="^[a-zA-Z0-9_/. -]\+\$"
@@ -47,13 +55,13 @@ if [ "$1" = "reinvoked" ]; then
   shift # Drop the call to simplesnapwrap
 
   # Validate again.  Just to be sure.
-  echo ".$*" | grep -q "${PATTERN}" || exiterror "Invalid characters found on re-validate; pattern is ${PATTERN}"
-  echo ".$*" | grep -vq '\.\.' || exiterror "Found .. in input; aborting."
+  echo ".$*" | $GREP -q "${PATTERN}" || exiterror "Invalid characters found on re-validate; pattern is ${PATTERN}"
+  echo ".$*" | $GREP -vq '\.\.' || exiterror "Found .. in input; aborting."
 
   # We don't want any paramters to contain a space or leading dash.
   for ARG; do
-    echo ",${ARG}" | grep -vq '^,-' || exiterror "Found leading '-' in parameter \"${ARG}\"; aborting."
-    echo ",${ARG}" | grep -vq ' ' || exiterror "Found space in parameters; aborting."
+    echo ",${ARG}" | $GREP -vq '^,-' || exiterror "Found leading '-' in parameter \"${ARG}\"; aborting."
+    echo ",${ARG}" | $GREP -vq ' ' || exiterror "Found space in parameters; aborting."
   done
   MODE="$1"
   shift || exiterror "Missing mode."
@@ -61,15 +69,15 @@ if [ "$1" = "reinvoked" ]; then
     "listfs")
        logit "Listing ZFS datasets without ${EXCLUDEPROP}=on"
        $ZFS list -t filesystem,volume -o "name,${EXCLUDEPROP}" -H | \
-          grep -v $'\ton$' | sed $'s/\t.*$//'
+          $GREP -v $'\ton$' | $SED $'s/\t.*$//'
        ;;
     "sendback")
        # Next lines shared with reap
        TEMPLATE="__simplesnap_$1_"
        TEMPLATEPATTERN="^[a-zA-Z0-9_]\+\$"
-       echo "_$TEMPLATE" | grep -q "${TEMPLATEPATTERN}" || exiterror "Invalid characters in sendback template; pattern is ${TEMPLATEPATTERN}"
+       echo "_$TEMPLATE" | $GREP -q "${TEMPLATEPATTERN}" || exiterror "Invalid characters in sendback template; pattern is ${TEMPLATEPATTERN}"
        DATASET="$2"
-       echo "_${DATASET}" | grep -vq " " || exiterror "Space found in dataset name"
+       echo "_${DATASET}" | $GREP -vq " " || exiterror "Space found in dataset name"
        [ -z "${DATASET}" ] && exiterror "No dataset given."
        [ -z "$1" ] && exiterror "No template given."
 
@@ -83,7 +91,7 @@ if [ "$1" = "reinvoked" ]; then
        fi
 
        # Make a new snapshot.
-       NEWSNAP="${TEMPLATE}`date +%FT%T`__"
+       NEWSNAP="${TEMPLATE}`$DATE +%FT%T`__"
        NEWFULLSNAP="${DATASET}@${NEWSNAP}"
        logit "Making snapshot ${NEWFULLSNAP}"
        $ZFS snapshot "${NEWFULLSNAP}"
@@ -102,9 +110,9 @@ if [ "$1" = "reinvoked" ]; then
        # Next lines shared with sendback
        TEMPLATE="__simplesnap_$1_"
        TEMPLATEPATTERN="^[a-zA-Z0-9_]\+\$"
-       echo "_$TEMPLATE" | grep -q "${TEMPLATEPATTERN}" || exiterror "Invalid characters in reap template; pattern is ${TEMPLATEPATTERN}"
+       echo "_$TEMPLATE" | $GREP -q "${TEMPLATEPATTERN}" || exiterror "Invalid characters in reap template; pattern is ${TEMPLATEPATTERN}"
        DATASET="$2"
-       echo "_${DATASET}" | grep -vq " " || exiterror "Space found in dataset name"
+       echo "_${DATASET}" | $GREP -vq " " || exiterror "Space found in dataset name"
        [ -z "${DATASET}" ] && exiterror "No dataset given."
        [ -z "$1" ] && exiterror "No template given."
         
@@ -115,7 +123,7 @@ if [ "$1" = "reinvoked" ]; then
        else
          for REMOVAL in ${SNAPSTOREMOVE}; do
             logit "Destroying snapshot ${REMOVAL}"
-            echo "_${REMOVAL}" | grep -q '@' || exiterror "PANIC: snapshot name doesn't contain '@'"
+            echo "_${REMOVAL}" | $GREP -q '@' || exiterror "PANIC: snapshot name doesn't contain '@'"
             $ZFS destroy "${REMOVAL}"
          done
        fi
@@ -138,8 +146,8 @@ fi
 
 # Sanitize input.  We don't want special characters here.
 
-echo ".${CMD}" | grep -q "${PATTERN}" || exiterror "Invalid characters in input; pattern is: ${PATTERN}"
-echo ".${CMD}" | grep -vq '\.\.' || exiterror "Found .. in input; aborting."
+echo ".${CMD}" | $GREP -q "${PATTERN}" || exiterror "Invalid characters in input; pattern is: ${PATTERN}"
+echo ".${CMD}" | $GREP -vq '\.\.' || exiterror "Found .. in input; aborting."
 
 logit "Reinvoking to parse parameters"
 exec "$0" reinvoked ${CMD}
