bugfixes

diff --git a/simplesnapwrap b/simplesnapwrap
--- a/simplesnapwrap
+++ b/simplesnapwrap
@@ -75,7 +75,7 @@ if [ "$1" = "reinvoked" ]; then
        # Next lines shared with reap
        TEMPLATE="__simplesnap_$1_"
        TEMPLATEPATTERN="^[a-zA-Z0-9]\+\$"
-       echo "_$TEMPLATE" | $GREP -q "${TEMPLATEPATTERN}" || exiterror "Invalid characters in sendback template; pattern is ${TEMPLATEPATTERN}"
+       echo "a$1" | $GREP -q "${TEMPLATEPATTERN}" || exiterror "Invalid characters in sendback template \"$1\"; pattern is ${TEMPLATEPATTERN}"
        DATASET="$2"
        echo "_${DATASET}" | $GREP -vq " " || exiterror "Space found in dataset name"
        [ -z "${DATASET}" ] && exiterror "No dataset given."
